### ISSUE TITLE
iOS: App muss Daten vom Backend/Server dynamisch holen

### ISSUE THREAD

**Issue by MichaelRoethlin** [particip-app/issues#10]
Dies betrifft
- strukturierte Daten
- Bilder

Funktionsweise analog Android: 
1. beim Aufstarten wird automatisch Verbindung zum Server aufgenommen und geschaut, ob es Updates gibt
2. Sobald die Updates herunter geladen wurden, werden die Ansichten (Liste/Details) aktualisiert
3. Bilder werden wie bei Android nur auf Anfrage vom Server heruntergeladen.

**Comment by Kristinaherbst** [comment]
Tablet IOS: wenn man unter Einstellungen alle Bilder runterladen geklickt hat, werden zwar alle Bilder der Liste geladen, aber im Detail sind sie nicht ansehbar (kein Bild zu sehen) wenn man offline geht. Bzw. die Bilder welche man Online aufgerufen hatte, sind offline auch noch sichtbar- andere nicht.

**Comment by Kristinaherbst** [comment]
Wenn man die App das erste Mal startet, geht der User nicht einfach davon aus, dass man die App auch offline ansehen kann? Eigentlich müsste es doch genau andersrum sein- erst wenn der User den Download nicht wünscht, werden die Daten nicht gedownloaded. Sonst wundert man sich beim Offlinebetrieb, warum die Bilder nicht da sind? Oder falsch? Vielleicht müsste man mit einem Popup über diesen Sachverhalt hinweisen???

**Comment by Kristinaherbst** [comment]
Tablet: Auch wenn man nach Offline Betrieb wieder online geht, werden die Bilder nicht geladen.

**Comment by MichaelRoethlin** [comment]
Siehe dazu den neuen Issue #82.
