### ISSUE TITLE
IOS Datenaktualisierung: Verbergen / Anzeigen von Objekten

### ISSUE THREAD

**Issue by Kristinaherbst** [particip-app/issues#103]
**Umgebung:** 
IOS 5 S
**Zeitpunkt:** 
20.7. 16:30h
**Version:** 
letzte Testflight vom Juli (1.0.2 (9))
### Expected behaviour
- ein ehemals verborgenes Objekt im Backend (bSp. Flug) wird wieder in der App angezeigt nachdem es im Backend "freigegeben" wurde
  ### Actual behaviour
- wird nicht in der App angezeigt; nicht synchron mit Backend
### Steps to reproduce
- Backend: Bsp. Flug Lampe Verbergen anmachen (so dass es also gezeigt wird)
- in der App: Datenaktalisierung durchführen
- Objekt suchen in der Liste (wird dann aber nicht angezeigt)

**Comment by MichaelRoethlin** [comment]
Das System ist gnadenlos: im Feld Canton des Flug-Eintrags war fehlerhafterweise `Bern` statt `BE` eingetragen; die iOS-App filtert nach Kantonskürzel gem. Einstellungen und hat deshalb im Standard nur `BE` und `FR` angezeigt, nicht aber Einträge mit `Bern` ...

Nach Korrektur des Flug-Eintrags im Typo3 funktioniert dies einwandfrei, mit der Glühbirne kann ein- und ausgeschaltet und synchronisiert werden.  

![flug-be](https://cloud.githubusercontent.com/assets/4992205/17017461/b1ac0e06-4f33-11e6-9900-19d6486e61fe.png)
