### ISSUE TITLE
IOS Datenaktualisierung: Artistlink von Artwork entfernen

### ISSUE THREAD

**Issue by Kristinaherbst** [particip-app/issues#104]
Umgebung: IOS

Version: Testfight 9

Expected behaviour

Gelöschte bzw. nicht referenzierte Künstler sind für den Benutzer dennoch sichtbar aber eben nicht verlinkt

Actual behaviour
im Backend entfernte Verlinkungen auf Künstler sind für den Benutzer sichtbar aber der Link bleibt anklickbar. 

Steps to reproduce

Im Backend Link auf Künstler k an Artwork a anfügen
IOS, Datensynchronisation
IOS, prüfen, dass Link auf Artwork a Künstler k hat
Im Backend Künstler k von Artwork a wegnehmen
IOS, Datensynchronisation
IOS, prüfen, dass Artwork a Link auf Künstler k nicht mehr hat

**Comment by MichaelRoethlin** [comment]
OK, ich glaube, ich sehe hier, was passiert: Verweise werden unabhängig davon, ob sie vom Server als gelöscht gemeldet werden, als "sichtbar" wiederhergestellt. Ich muss in der iOS-Version das gelöscht-Feld bei der Synchronisation beachten!
