### ISSUE TITLE
Bug IOS: erstes Aufstarten zeigt bilderlose Liste 

### ISSUE THREAD

**Issue by Kristinaherbst** [particip-app/issues#17]
Nach dem Download der App, bevor der Startscreen eingeblendet wird, erscheint die Liste für einen kurzen Moment (ohne Bilder). Dies verwirrt- hier muss sauber nur der Startbildschirm kommen. (danach wie gesagt, die Frage des Downloads der Bilder auf das Telefon oder nicht..... vgl. Issue 10)

**Comment by MichaelRoethlin** [comment]
Ja, ... das ist nichts Neues, war vorher auch schon so. Die Erststartbildschirme überdecken die Liste, das sieht man beim ersten Start je nach Handy schon, stört. Mal schauen, ob man das einfach wegbekommt.

**Comment by MichaelRoethlin** [comment]
Ich habe mit 1.0.2 (3) eine Verzögerung eingebaut, sodass bei den meisten Geräten jetzt nichts mehr zu sehen ist. Ich schliesse mal, behalte es aber im Auge.
