### ISSUE TITLE
iOS: Karte Global braucht zu lange um zu laden

### ISSUE THREAD

**Issue by Kristinaherbst** [particip-app/issues#18]
Die Karte erscheint (auch bei WLAN) erst nach recht langer Zeit- ich weiss das aber ein User würde ungeduldig werden.

**Comment by MichaelRoethlin** [comment]
Die Karte würde viel schneller starten, wenn der Ausschnitt hineingezoomt würde. Die Detailkarten starten nämlich sehr schnell. Ich schaue mal.
