### ISSUE TITLE
Liste IOS: Die Sortierung der Liste beim Öffnen

### ISSUE THREAD

**Issue by Kristinaherbst** [particip-app/issues#19]
Die Sortierung der Liste- sollte nicht das nächste Objekt oben stehen, wenn man öffnet?

**Comment by MichaelRoethlin** [comment]
Ja, wenn die Positionsinfo da ist, was sicher nicht in 100% der Fällen beim App-Start der Fall ist. Es kann 10-20 Sekunden gehen, bis die Position verfügbar ist, in Gebäuden insbesondere. Wie gesagt würde ich gerne einen Indikator zeigen, der die Standortermittlung visualisiert.

**Comment by Kristinaherbst** [comment]
@MichaelRoethlin: Ein Wartezeichen für die Standortermittlung? - warum nicht. aber wo willst Du das hinpacken?

**Comment by MichaelRoethlin** [comment]
Stimmt, das sind sich die Leute nicht gewohnt ... und wissen sicher auch, dass die Positionierung Zeit braucht und nicht immer stimmt (permanente Kompassfehler). Lassen wir das erstmal weg.
