### ISSUE TITLE
IOS Tablet:  Suchergebnisse gelöscht, wenn Global Karte 

### ISSUE THREAD

**Issue by Kristinaherbst** [particip-app/issues#20]
Wenn man in das Suchfeld etwas eingetragen hat, danach auf den Button Global Karte geht um die Suchergebnissse anzuzeigen, wird meine Suche gelöscht. Der Suchbegriff muss oben stehen bleiben, die Karte muss die Suchergebnisse anzeigen und erst wenn man die Suche abbricht, sollten alle Objekte wieder in Liste und Karte erscheinen. 
Auch wenn man die Karte anklickt im Detail, wird der Eintrag im Suchfeld gelöscht- die Global Karte macht das eben auch; resp. sie reagiert in dieser Situation garnicht.

**Comment by MichaelRoethlin** [comment]
OK, das ist ein Anzeigeproblem auf Tablets. Die Suchliste wird nicht gelöscht, bleibt erhalten und wird wieder aktiviert, sobald ich links auf ein Werk clicke. Dass im Suchfeld einfach "Suche" steht statt der Suchbegriff, ist unschön. Schaue ich an.

**Comment by MichaelRoethlin** [comment]
Siehe dazu neuen Issue #84.
