### ISSUE TITLE
Tablet IOS: Bild Gross von Detail erscheint nicht

### ISSUE THREAD

**Issue by Kristinaherbst** [particip-app/issues#21]
wenn man ein Bild aus dem Detail auf Grossformat anklickt, erscheint nur der Platzhalter. Erst beim zweiten Mal (der selbe Vorgang: ins selbe Detail gehen, Bild anklicken) erscheint das Bild in gross.

**Comment by MichaelRoethlin** [comment]
Oder wenn man (wenn mehrere Bilder pro Werk vorhanden) ins 2. oder 3. Bild nach rechts geht, dann etwas wartet, dann wieder nach links geht. Es braucht einfach etwas Zeit; man sollte dies als Benutzer wahrnehmen, evtl. ein Platzhalter mit "bitte warten".

**Comment by MichaelRoethlin** [comment]
Siehe dazu Issue #80.
