### ISSUE TITLE
Tablet IOS: Melden Global (extrem)

### ISSUE THREAD

**Issue by Kristinaherbst** [particip-app/issues#22]
Wenn man ein eingefügtes Bild austauschen möchte, lässt sich der Schriftzug (Auswahl Kamera...) nicht anklicken- erst nach mehrmal die Schaltfläche absuchen reagiert die Auswahl. Wenn man dann das Bild ausgetauscht hat, verschwindet der eingetragene Text bei Beschreibung wieder....

Mir scheint, das Formular erlaubt nur das chronologische Eintragen von oben nach unten??? Ansonsten löscht es bereits eingefügte Einträge wieder?

**Comment by Kristinaherbst** [comment]
Wenn man dann auf senden geht, erscheint auch bei 0% des Sendstatus die Meldung dass es gesendet ist? Der Balken unten müsste sich doch anpassen auf 100% ?

**Comment by MichaelRoethlin** [comment]
Jupp, schaue ich an, an dem Formular habe ich sehr viel umgestellt, da ist noch nicht wieder alles im Lot. Besten Dank!

**Comment by Kristinaherbst** [comment]
Hallo Du Nachtarbeiter!

**Comment by MichaelRoethlin** [comment]
Ersetzt durch Issues #26 und #27.
