### ISSUE TITLE
Silver Lining: @2x- und @3x-Qualitäten fehlen noch

### ISSUE THREAD

**Issue by MichaelRoethlin** [particip-app/issues#23]
- Funktioniert: http://particip-app.bfh.ch/service/apiv1/file/katalog/thumbs_generated_ios/thumb-02-032.png
- Funktioniert nicht: http://particip-app.bfh.ch/service/apiv1/file/katalog/thumbs_generated_ios/thumb-02-032@2x.png
- Funktioniert nicht: http://particip-app.bfh.ch/service/apiv1/file/katalog/thumbs_generated_ios/thumb-02-032@3x.png

**Comment by zasu3** [comment]
Sind generiert und funktionieren
