### ISSUE TITLE
Weitere fehlende @3x-Qualitäten

### ISSUE THREAD

**Issue by MichaelRoethlin** [particip-app/issues#24]
- http://particip-app.bfh.ch/acms/fileadmin//katalog/thumbs_generated_ios/thumb-01-171@3x.png
- http://particip-app.bfh.ch/acms/fileadmin//katalog/thumbs_generated_ios/thumb-01-172@3x.png
- http://particip-app.bfh.ch/acms/fileadmin//katalog/thumbs_generated_ios/thumb-02-031@3x.png

**Comment by zasu3** [comment]
Diese fehlen nicht mehr, aber wahrscheinlich gibt es andere Fehler.
