### ISSUE TITLE
Falscher Content-Type Notification API

### ISSUE THREAD

**Issue by ukeller** [particip-app/issues#25]
Michael kannst du das Prüfen?

Im Android Code sehe ich folgendes:
"data:image/png;base64," + base64EncodedImage

Allerdings wird das Bild in Realität in Jpeg kodiert.
Die Preview im Mail funktioniert trotz des eigentlich falschen Content-Types.
Folgendes Script macht 4 Notifications. Davon kommen nur die an mit `Content-Type image/png` (rot und grün), egal ob es ein JPEG oder PNG ist.

``` bash
#!/bin/bash
sendTest() {
    CONTENT_TYPE=$1
    IMAGE_TYPE=$2
    color=$3
    id="content type test $1 $2 $3"
    tmpImage="/tmp/test_out.${IMAGE_TYPE}"
    echo $tmpImage
    convert -size 1x1 xc:${color} $tmpImage
    image="data:${CONTENT_TYPE};base64,$(base64 $tmpImage)"
    content="{\"notifyFormObject\":\"Kirchenfenster\",\"notifyFormCoord\":\"\n\",\"notifyFormCameraInput\":\"${image}\",\"notifyFormDescr\":\"[pARTicip] Artwork has a defect\n$id\"}"    
    echo "***************************************"
    echo "$id"
    file $tmpImage
    echo "$content"
    curl -X POST -d "$content" 'http://particip-app.bfh.ch/service/apiv1/notification' -H 'Content-Type: application/json' -H  'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36' -H 'Accept: application/json'    
}

sendTest image/png  jpeg green
sendTest image/png  png  red
sendTest image/jpeg jpeg blue
sendTest image/jpeg png  pink
```

**Comment by MichaelRoethlin** [comment]
Salut Urs

Besten Dank für den Hinweis und auch den super Testcode!! Tatsächlich war bisher das Backend nur für den Empfang von PNGs vorbereitet, was ohne Probleme aber geändert werden kann. Eine JPG-Datei wurde unbesehen davon geschrieben, ob es gültige Grafikdaten sind.

Ich habe jetzt `image/jpg` und `image/jpeg` zusätzlich im Backend zugelassen.

Funktioniert das Senden bei dir jetzt auch wie gewünscht? Du kannst immer alles auf dem Server gespeicherte über http://particip-app.bfh.ch/acms/fileadmin/user_upload/notifications/ einsehen.

Herzlichen Dank und einen schönen Sonntag

Michael

Vorher:

>  $rawimage = str_replace ("data:image/png;base64,", "", $objdata->notifyFormCameraInput);

Jetzt (inkl. zusätzliches Error Handling):

> ```
>         $datasets['meta']['status'] = ServiceControllerV1::ERR_OK;
>         $datasets['meta']['message'] = 'OK';
> 
>         if (isset($objdata->notifyFormCameraInput)) {
>             $rawimage = str_replace (["data:image/png;base64,", "data:image/jpg;base64,", "data:image/jpeg;base64,"], "", $objdata->notifyFormCameraInput);
>             $filepath = $tmpfile . '.jpg';
>             file_put_contents ($tmpfile . '.jpg', base64_decode ($rawimage));
>             if(exif_imagetype($filepath) != IMAGETYPE_JPEG){
>                 $datasets['meta']['status'] = ServiceControllerV1::ERR_OTHER_PROBLEM;
>                 $datasets['meta']['message'] = 'Saved file is NOT a JPEG image';
>             } else {
>                 $datasets['meta']['message'] = 'OK - and valid JPG file written';
>             }
>             $objdata->notifyFormCameraInput = "(converted and put into " . $downloadlinkImg . ")";
>             $resString .= "Bildlink unter:      " . $downloadlinkImg . PHP_EOL;
>             unset($objdata->notifyFormCameraInput);
>         }
> ```

**Comment by MichaelRoethlin** [comment]
Zusammenfassung:
- Android-Geräte (oder andere) möchten auch Bilder mit image/jpg resp. image/jpeg schicken (aber immer JSON-encoded), anstatt nur image/png
- das Backend hat bisher die Bilder als *.jpg-Datei gespeichert, aber es war eigentlich „nur“ PNG drin (was komischerweise im Mail und Browser zu keinen Problemen führt)
- NEU
  — werden vom Backend auch image/jpg und image/jpeg als gesendete Bilder entgegengenommen (analog image/png)
  — werden alle Bilder als *.png abgespeichert und auch so deklariert, in Mail und Maillink (Bild öffnet sich dann per Link im Browser)
  — wird in der JSON-Antwort vom Webservice auch bestätigt, dass die PNG-Datei einwandfrei gespeichert werden konnte

Achtung: die Darstellung der 1x1-Bilder wird im E-Mail sehr vergrössert, in der Browser-Darstellung hingegen nicht. Deshalb kann der „pinkige Pixel“ in der Browser-Darstellung kaum sichtbar sein, ist aber schon da!

**Comment by ukeller** [comment]
Aus meiner sicht IO.
