### ISSUE TITLE
Knopf, manuelle Synchronisation

### ISSUE THREAD

**Issue by ukeller** [particip-app/issues#37]
Aktuell wird auf Android nur nach Neustart der App synchronisiert.

Auf IOS gibt es in den Einstellungen eine Möglichkeit zum manuellen Abgleich der Daten.
Soll dies auf Android auch so sein?
Wo soll dieser platziert werden?
Wäre es möglich, einen Screenshot von IOS zu bekommen?

**Comment by ukeller** [comment]
@MichaelRoethlin kannst du das beantworten?

**Comment by ukeller** [comment]
Screenshot Android:
![simulator screen shot 31 05 2016 07 03 40](https://cloud.githubusercontent.com/assets/2203775/15689829/11060e4a-2781-11e6-8b67-1ee5dd48862d.png)

**Comment by ukeller** [comment]
@Kristinaherbst  kannst du das validieren?

Screens aus Android
<img width="807" alt="screen shot 2016-05-31 at 23 31 05" src="https://cloud.githubusercontent.com/assets/2203775/15691225/cccc33a6-2787-11e6-9d1b-ca2f0e1c9f71.png">
<img width="807" alt="screen shot 2016-05-31 at 23 31 08" src="https://cloud.githubusercontent.com/assets/2203775/15691224/cccb900e-2787-11e6-8056-4acda0e61557.png">

**Comment by ukeller** [comment]
revaultch/participate@cd6d5340ae3a9bd49d03c6e781c0cf9973579451

**Comment by Kristinaherbst** [comment]
@ukeller : vielen Dank, dass sieht gut aus.
