### ISSUE TITLE
Bug Tablet IOS: Bild

### ISSUE THREAD

**Issue by Kristinaherbst** [particip-app/issues#4]
ein Bild wird erst beim zweiten Mal antippen vergrössert

**Comment by MichaelRoethlin** [comment]
Ich habe das grade auf dem iPad Mini getestet:
- Aus dem Detail in den Vollbildmodus klappt bei mir (und den gewählten Beispielen Eisenplastik von Jean-Jaques Hofstetter sowie Silver Lining immer beim **ersten** Antippen
- Sobald man im Vollbildmodus ist, muss immer per Doppelclick hineingezoomt werden; dies ist gewollt, aus meiner Sicht der Standard und auch an anderer Stelle wie bei der Kartenfunktion immer genau so. 

Aus meiner Sicht ein Feature und gewollt!?

**Comment by MichaelRoethlin** [comment]
Ich schliesse das erstmal!
