### ISSUE TITLE
IOS Tablet Version 1.0.2 (3): Bilder on/offline

### ISSUE THREAD

**Issue by Kristinaherbst** [particip-app/issues#40]
Wenn der User Offline ist, sollte der Hinweis erscheinen, dass die Bilder im Detail nur mit WLAN einsehbar sind / resp. man sie downloaden muss. Oder?

**Comment by MichaelRoethlin** [comment]
Hmm, kann man diskutieren, einen "Achtung offline-Hinweis" (d.h. weder "Mobile Daten" noch WLAN etc.). Die Android-Version hat m.E. auch keinen Hinweis, war bisher kein Problem. 
Auch bei der Karte stellt sich diese Frage, die funktioniert bisher nirgends offline.

**Comment by Kristinaherbst** [comment]
Vielleicht sollte man am Anfang darauf hinweisen, dass Karten und Bildmaterial nur im Online Betrieb zugänglich sind? (ausser man downloaded sie- aber die Karten werden ja nicht runtergelassen, oder?)

**Comment by MichaelRoethlin** [comment]
Siehe Issues #81 sowie #82.
