### ISSUE TITLE
IOS Tablet Version 1.0.2 (3): Geschwindigkeit Anzeige der Bilder

### ISSUE THREAD

**Issue by Kristinaherbst** [particip-app/issues#41]
Die Bilder erscheinen alle mit Verzögerung und man sieht immer den Platzhalter- gefällt mir noch nicht so besonders gut.

**Comment by Kristinaherbst** [comment]
Auch wenn man ein Detail geöffnet hat und das Bild als Platzhalter da ist weil man offline ist, erscheint das Bild nicht sobald man Online geht. Man muss zuerst die Liste thumb anklicken, dass das Bild erscheint. Das Bild sollte mit dem Onlinegehen erscheinen ohne dass man es erneut in der Liste aufrufen muss.

**Comment by MichaelRoethlin** [comment]
Siehe für die Verfügbarkeits- resp. Offlineprobleme Issue #80.
