### ISSUE TITLE
IOS Tablet Version 1.0.2 (3): Melden

### ISSUE THREAD

**Issue by Kristinaherbst** [particip-app/issues#42]
Wenn man Text in das Meldeformular einträgt, bleibt der graue Vorlagetext stehen- der sollte doch auch beim reinklicken in das Feld verschwinden, oder?

**Comment by MichaelRoethlin** [comment]
Korrekt, der Text muss verschwinden, sobald in das Feld geklickt wird. Ist gefixt.
