### ISSUE TITLE
IOS Tablet Version 1.0.2 (3): Bild Vergrössern

### ISSUE THREAD

**Issue by Kristinaherbst** [particip-app/issues#43]
Sobald man eines der Detailbilder vergrössern möchte, erscheint im Vollformat nur der Platzhalter. Allerdings passiert dies nicht bei jedem Mal so. Wenn man es an unterschiedlichen Objekten probiert, passiert dies immer wieder.

**Comment by Kristinaherbst** [comment]
Vor allem passiert dies, wenn man das 2. Bild (von z.B. 3)  vergrössern möchte- dann ist es nicht da.

**Comment by MichaelRoethlin** [comment]
Siehe dazu #80 .
