### ISSUE TITLE
IOS Tablet Version 1.0.2 (3): Suche- dann Ergebnisse auf Karte 

### ISSUE THREAD

**Issue by Kristinaherbst** [particip-app/issues#45]
Die Suchergebnisse lassen sich zwar auf der Karte Global anzeigen aber der Betreff der Suchzeile soll nicht einfach gelöscht sein. Zudem wenn man die Suche neu aufsetzt, wird die Karte nicht aktualisiert, auch nicht wenn man erneut den Kartenbutton anklickt. Erst wenn man ein Detail angesehen hat und wieder auf die Karte Global klickt, wird es richtig angezeigt.
Sobald man dann ein Bild auf der Suchergebnisliste anklickt, verschiebt sich bei mir die ganze Liste nach unten und oben bleibt ein weisses Feld stehen.

**Comment by MichaelRoethlin** [comment]
Siehe dazu neuen Issue #84.
