### ISSUE TITLE
IOS Store: Suche

### ISSUE THREAD

**Issue by Kristinaherbst** [particip-app/issues#47]
Wenn man im Store nach Particip sucht, findet man die App nur unter ihrem Namen. Kann man dort die Suchschlagworte anpassen? so findet man das App nur wenn man den Namen genau eingibt?

**Comment by Kristinaherbst** [comment]
@ukeller @MichaelRoethlin 
Für das Erscheinen des Artikels in der BZ, wäre es toll, wenn diese Anpassung noch gemacht werden könnte. Schlagworte bei der Suche sollten sein:
public art
Kunst im öffentlichen Raum
particip
partizip
participate
Bern
Freiburg
Kunst
Wäre es möglich dies auch für den Store Android zu optimieren? Ein paar der Schlagwörter sind bereits schon eingegeben... aber es fehlen doch noch ein paar.

**Comment by ukeller** [comment]
Nehme Android hier raus. Dort gibt's keine Keywords, sie werden aus dem Beschreibungstext extrahiert, auf diesen hast du ja bereits Zugang in der Konsole.

**Comment by MichaelRoethlin** [comment]
Wunsch ist notiert; 

Bisher:

```
Kunst, Bern, Freiburg
```

**Neu:**

```
Kunst, Bern, Freiburg, Public Art, Kunst im öffentlichen Raum, particip, partizip, participate
```

Bestimmungen im App-Store (Änderungen sind erst mit kommender Version wirksam):

```
App-Informationen
Diese Informationen werden für alle Plattformen dieser App verwendet. Änderungen werden mit der nächsten Version Ihrer App veröffentlicht.
```
