### ISSUE TITLE
IOS Tablet Version 1.0.2 (3): Datenaktualisierung Absturz

### ISSUE THREAD

**Issue by Kristinaherbst** [particip-app/issues#48]
Bei der Datenakualisierung ist die App abgestürzt.

**Comment by Kristinaherbst** [comment]
Synchronisierung mit Daten im Backend ist nicht erfolgt (z.B. Verlinkung auf Beton bei Radelfinger und Heinz Brand)

**Comment by MichaelRoethlin** [comment]
Siehe dazu neues Issue #83.
