### ISSUE TITLE
Bug Tablet IOS: Zugriff Bilderbibliothek

### ISSUE THREAD

**Issue by Kristinaherbst** [particip-app/issues#5]
Wenn man auf die Bilder in der Bibliothek zugreift, verwendet das Tablet Querformat

**Comment by MichaelRoethlin** [comment]
Genau, und das iPhone verwendet nur Hochformat! 

Das ist vom System vorgegeben, die Darstellung der System-Bilderbibliothek lässt sich leider durch eine App nicht ändern, man muss halt dann rasch manuell mitkippen ...
