### ISSUE TITLE
Daten allg: Zuordnung Klangbrücke von Max Neuhaus

### ISSUE THREAD

**Issue by Kristinaherbst** [particip-app/issues#52]
Ich komme hier nicht nach, was in Typo3 falsch ist? Die Bilder werden in der App so nicht angezeigt wie im Backend gedacht...

**Comment by MichaelRoethlin** [comment]
Liebe Kristina! Mit vereinten Kräften hat Sabine es gestern hinbekommen, die richtige Grafik zu setzen. Der Verdacht, dass das Bild ersetzt wurde und die Vorschau noch vom ursprünglichen stammte, war zutreffend. Nun stimmt die Klangbrücke, und auch die "Maillart Extended" von Serra ist bildmässig korrigiert und jetzt auf dem richtigen Stand!
