### ISSUE TITLE
IOS: Datenakutualisierung

### ISSUE THREAD

**Issue by Kristinaherbst** [particip-app/issues#53]
Ich habe soeben ein neues Objekt im Backend eingetragen ohne es zu verbergen. Es erscheint aber nicht in der nochmals gedownloadedeten App und auch nicht bei Testflight. ("Flug" von Werner Witschi, Originalkey 33)

**Comment by MichaelRoethlin** [comment]
Das ist das `hidden`-Phänomen (aka gelbe/weisse Glühbirne), welches jetzt mit einem Webservice-Umbau gelöst sein sollte, s. [Beschreibung](https://github.com/particip-app/issues/blob/master/DataProvisioning.md#22-artwork-entity-lifecycle-web-service-behavior).

**Comment by MichaelRoethlin** [comment]
Wird gelöst sein mit #78 .
