### ISSUE TITLE
IOS: Startscreens erscheinen nicht

### ISSUE THREAD

**Issue by Kristinaherbst** [particip-app/issues#54]
ich habe mir aus der Cloud die App erneut runtergeladen, jedoch erscheinen die Startbildschirme nicht. Sollten doch aber, oder?

**Comment by MichaelRoethlin** [comment]
Die Startbildschirme erscheinen nur beim ersten Start. Bei einem Update der App (wenn du das mit dem "erneut runterladen" meinst) bleiben die Daten erhalten (z. B. Favoriten), deshalb sollen die beiden Startbildschirme nicht mehr ein zweites Mal erscheinen. Wenn die App neu _gelöscht_ und neu installiert wird, erscheinen die Startbildschirme neu. Wenn es nicht so wäre, ist es ein Bug!

**Comment by MichaelRoethlin** [comment]
Ich nehme das als Test für den nächsten Release auf, wenn es immer noch wie von mir beschrieben funktioniert (hat es bisher), werde ich das Ticket gerne schliessen.
