### ISSUE TITLE
Android Test 07.06.: Distanz falsch angezeigt nach Datenaktualisierung

### ISSUE THREAD

**Issue by Kristinaherbst** [particip-app/issues#55]
Sobald man im Menü unter Einstellungen etwas verändert (z.B. Datenakutalisierung oder lokales Speichern), wird die Distanzanzeige auf der Liste vollständig falsch angezeigt. Die Distanzen stimmen nicht mehr; Absturz nachdem ich im Detail auf Karte gegangen bin (hier war der aktuelle Standort aber richtig angezeigt)

**Comment by Kristinaherbst** [comment]
Wenn man dann bei den Objekten wieder etwas hin und her geklickt hat, reorganisiert sich die Distanzanzeige wieder richtig (alles im WLAN), aber sobald ich bspw. nur kurz den Bildschirm ausgehen lasse und wieder die App öffne (Bildschirm einfach wieder aktiviere) ist die Distanz erneut durcheinander (SONY Experia Smartphone)

**Comment by ukeller** [comment]
~~Kannst du daraus zwei Issues machen und diesen schliessen. Also 1x Crash und 1x Distanz.~~

**Comment by ukeller** [comment]
Die beschriebenen Probleme haben technisch mit der Synchronisation nichts zu tun.

Bei der Neu-Berechnungen der Distanzen gibt es anscheinend mehrere Probleme:
- Ist das GPS beim Start nicht verfügbar werden die Distanzen erst nach einem Hintergrund/Vordergrund der App neu berechnet.
- Ist das GPS nicht verfügbar sind die Distanzen 0km beim ersten Start
- Das Location-Update scheint nicht regelmässig ausgelöst zu werden
- Die Liste wird nach einem Location-Update nicht automatisch aktualisiert, erst ein neues Klicken auf Übersicht oder Suche bringt die Liste mit den neuen Distanzen

Dies hat zur Folge, dass man die Distanz neuer Kunstwerke erst sieht, wenn man folgende Manipulationen am UI vornimmt:
- Backend: Einpflege eines neuen Kunstwerks
- Android Settings / Datenaktualisierung
- Warten bis die Statusanzeige verschwindet
- Navigieren zur Übersicht
- Hintergrund/Vordergrund
- Erneuter Klick auf Übersicht

Zusätzlich zu den genannten Problemen wird die Liste im UI nochmals "visuell" sortiert
