### ISSUE TITLE
Android Test 07.06: Datenaktual. funktioniert nicht

### ISSUE THREAD

**Issue by Kristinaherbst** [particip-app/issues#56]
Ich habe im Backend ein Objekt verborgen und es wird auch nach Datenaktualisierung dennoch in der App angezeigt.

**Comment by ukeller** [comment]
Ich kann hier nur vermuten, dass es sich um das Objekt "Maillart Extended" handelt.
Dieses ist bei euch in den Daten doppelt vorhanden. Einmal gelöscht und einmal nicht gelöscht.
Die Uids sind 49560 respektive 49594.

```
curl -s http://particip-app.ch/service/apiv1/artwork |jq '.record[]|select(.deleted==1)| [.uid, .title, .sys_language_uid, .deleted]'
```

[  49594,  "Maillart Extended",  0,  1]
[  49714,  "Les trois marguerites",  0,  1]
[  49715,  "Trojanisches Pferd",  0,  1]

```
curl -s http://particip-app.ch/service/apiv1/artwork |jq '.record|.[] | select(.title | contains("Maillart")) | [.uid, .title, .sys_language_uid, .deleted]'
```

[  49560,  "Maillart Extended",  0,  0]
[  49594,  "Maillart Extended",  0,  1]

**Comment by Kristinaherbst** [comment]
Auch bei der Version 2adc69b: Objekt Flug ist im Backend verborgen markiert, aber in der App sichtbar.

**Comment by ukeller** [comment]
Im API kommt das Objekt nicht als gelöscht.

```
 curl -s http://particip-app.ch/service/apiv1/artwork |jq '.record|.[] | select(.title | contains("Flug")) | [.uid, .title, .sys_language_uid, .deleted]'
```

[  49899,  "Flug",  0,  0 ]

**Comment by ukeller** [comment]
Aus meiner Sicht ein Datenproblem. Bitte prüfen und schliessen.

**Comment by Kristinaherbst** [comment]
@MichaelRoethlin. wie könnten wir das im Backend anpassen, dass es funktioniert? Flug ist mit Glühbirne "aus" versehen und erscheint bei IOS nicht aber bei Android.

**Comment by ukeller** [comment]
Für mein verständnis @Kristinaherbst @MichaelRoethlin könntet ihr mir sagen, was Glühbirne aus bzw ein bedeutet? Entspricht das dem Attribut `deleted` aus dem Service?

**Comment by Kristinaherbst** [comment]
Sorry. Die Glühbirne ist ein Symbol für das Verbergen in Typo3. Man kann dies in einer Listenansicht an/aus machen. Bei "aus" sollte es im Frontend verborgen sein.

**Comment by ukeller** [comment]
OK. @MichaelRoethlin Was ist die Auswirking im Service? Welches Attribut?

**Comment by Kristinaherbst** [comment]
@ukeller - das Synchronisieren von gelöschten Bildern funktioniert leider ebenfalls nicht. Eigentlich wollte ich die App Android jetzt freigeben und das Problem mit den Bilder und dem Absturz bei Android damit beheben, indem ich Bilder, wie z.B. bei "Weltpostdenkmal", das Dritte Squarebild im Backend einfach mal  lösche aber, die gelöschten Squares bleiben dennoch sichtbar in der App. Gleiche Problem wie mit den gelöschten Materialien. 
Vorgehen war wie folgt:
1. Löschen der Datei im Backend (Square 02_018_04 (da Img_02_018_04 stand nicht zur Verfügung), Speichern
1. Datenaktualisierung in der App Android
2. zur Übersicht
   Erwartet: das das Bild im Detail Weltpostdenkmal gelöscht ist, da es im Backend gelöscht ist
   Ergebnis: Bild bleibt sichtbar, App stürzt bei Anklicken ab.

**Comment by ukeller** [comment]
Kannst du daraus mehere Tickets machen und dieses schliessen? Hier sind schon zu viele verschiedene Dinge drin:
- Datenproblem gelöschtes Objekt #69, #70, #71, #68 
- IOS Problem @MichaelRoethlin bitte prüfen
- Materialien Problem #69
- Images nicht gelöscht #71 
- Weltpost, Bilder Absturz #71 #66 
- Künstler Problem #70

**Comment by ukeller** [comment]
Ersetzt durch neue Tickets. Eventuell für IOS prüfen, welche vorhanden sind.
