### ISSUE TITLE
Android Test 07.06: Objekt Balancierender Bär

### ISSUE THREAD

**Issue by Kristinaherbst** [particip-app/issues#57]
Hier fehlen die Abbildungen im Detail, welche aber im Backend vorhanden sind (bei IOS auch sichtbar im testflight).

**Comment by ukeller** [comment]
Es fehlen die Bilder im Format "square".
Die Android-App ist auf diese angewiesen. Bitte überprüfen.

**Comment by MichaelRoethlin** [comment]
Die Bilder sind drin!
- Im http://particip-app.ch/service/apiv1/image sind für das Objekt 02-016 7 Treffer drin: 1x Thumbnail, 3x Squares, 3x Images
- http://particip-app.ch/service/apiv1/file/katalog/squares_generated_ios/square-02-016-01.png etc. existiert
- http://catalog.particip-app.ch/de/artwork/49701 kann die Square-Bilder ebenfalls aufrufen

Sollte also klappen, siehst du sie über diesen Link?

**Comment by ukeller** [comment]
Die Bilder sind zwar da, aber das Timestamp unter /apiv1/image ist nicht aktuell!

```
curl -s http://particip-app.ch/service/apiv1/artwork |jq '.record|.[] | select(.title | contains("Balancierender")) | .uid'
```

49701

```
curl -s http://particip-app.ch/service/apiv1/image |jq '.record|.[]| select(.uid_artwork==49701).identifier'
```

"/katalog/squares_generated_ios/square-02-016-01.png"
"/katalog/images/img-02-016-01.jpg"
"/katalog/thumbs_generated_ios/thumb-02-016.png"
"/katalog/squares_generated_ios/square-02-016-02.png"
"/katalog/images/img-02-016-02.jpg"
"/katalog/squares_generated_ios/square-02-016-03.png"
"/katalog/images/img-02-016-03.jpg"

```
curl -s http://particip-app.ch/service/apiv1/image |jq '.meta.last_changed' | python -c "import sys, datetime; print(datetime.datetime.fromtimestamp(int(sys.stdin.readline())))"
```

2016-06-07 23:19:44

**Comment by MichaelRoethlin** [comment]
Der Timestamp 1465334384 der Tabelle "Image" betrifft ein neu hinzugefügtes Bild "/katalog/images/img-02-033-01.jpg" von Kristina; die Bilder des "Balancierenden Bär" sind aber schon seit längerem stabil und unverändert. 

Gibt es nur bei diesem Werk ein Bilderanzeigeproblem? (iOS hat m.E. keinerlei Probleme mit diesen 3 Squares ...)

**Comment by ukeller** [comment]
Meine Beobachtung
- Heute morgen hat das API die "Square"-Bilder nicht gelistet.
- Diese wurden im Verlauf des Vormittags zugefügt.
- Trotzdem zeigt das Timestamp auf gestern 23h20
- Die App synchronisiert daher die "Square"-Bilder nicht.

**Comment by MichaelRoethlin** [comment]
Ich selbst habe heute Morgen nichts an den Bildern gemacht, es gab lediglich eine Änderung um 2016-06-08 11:24:40 an der Tabelle Artwork. Die Bilder müssen in der Image-Tabelle immer drin gewesen sein.

Zum Vergleich: für die iOS-Version
- lese ich beim Update über http://particip-app.ch/service/apiv1/version den Versionsstand aller Tabellen
- sobald eine der Versionen älter ist als die bei mir lokal gespeicherte letzte Tabellenänderung, lade ich die Tabelle neu herunter.

Die Bilder haben auf dem Server alle Änderungsstand März, sind seit ungefähr damals auch solide eingebunden.

![02-016-server](https://cloud.githubusercontent.com/assets/4992205/15894645/4183f044-2d87-11e6-969d-8a3eef6be7e4.png)

**Comment by ukeller** [comment]
Ich habe das heute früh manuell überprüft. Ich bin mir 100% sicher, dass nur 4 Bilder vom API zurückgegeben wurden nämlich:

```
"/katalog/images/img-02-016-01.jpg"
"/katalog/images/img-02-016-02.jpg"
"/katalog/images/img-02-016-03.jpg"
"/katalog/thumbs_generated_ios/thumb-02-016.png"
```

Ich bin auch ganz sicher, dass ich auf der richtigen Infra war, da ich zuerst auf der falschen nachgeschaut habe.

# Auf der neuen Infra

Auf der neuen Infra (particip-app.ch) ist die Situation aktuell richtig: 

```
curl -s http://particip-app.ch/service/apiv1/image |jq '.record|.[]| select(.uid_artwork==49701)|.tstamp'|sort
```

1445330040
1447073322
1454957257
1456992154
1456992154
1457015624 
**1457015624**

**1457015625** entspricht dem **3. März 15h33**, gemäss deinem Screenshot, sollte max(timestamp) der Bilder für Artwork 49701 am **5. März** sein, hier ist also auch was faul.

```
curl -s http://particip-app.ch/service/apiv1/image |jq '.meta.last_changed'
```

1465334384 -> 7. Juni

```
curl -s http://particip-app.ch/service/apiv1/image |jq '.record|.[]| select(.tstamp > 1465334384)|.'
```

Kein Resultat. Korrekt

# Auf der alten Infra

Auf der alten Infra (particip-app.bfh.ch) lässt sich der Fehler von heute morgen noch nachvollziehen.
Es werden nur 4 Bilder angezeigt, obwohl nach deinem Screenshots die Bilder am 5. März alle vorhanden waren.
Die Bilder sollten also sowohl auf der neuen wie auch auf der alten Infrastruktur vorhanden sein, trotzdem gibt das API auf der alten Infra die Bilder nicht komplett zurück und ich gehe davon aus, dass dies auf der neuen Infra heute morgen ebenfalls der Fall war.

```
curl -s http://particip-app.bfh.ch/service/apiv1/image |jq '.record|.[]| select(.uid_artwork==49701)|.tstamp'|sort
```

1445330040 -> 20. Oktober
1447073322 
1456992154 
1456992154 ->  3. März 09h02

```
curl -s http://particip-app.bfh.ch/service/apiv1/image |jq '.meta.last_changed'
1464253228 -> 26. Mai
```

```
curl -s http://particip-app.ch/service/apiv1/image |jq '.record|.[]| select(.tstamp > 1464253228)|[.uid_file, .uid_artwork]'
```

Hier sollten keine Resultate zurückkommen
[ 3281,  49560]
[  4212,  49560]
[  4389,  49687]
[  4388,  49687]
[  5290,  49899]
[  5288,  49899]
[  5293,  49899]

**Comment by MichaelRoethlin** [comment]
Du, herzlichen Dank für die Abklärungen, Urs (du bist wirklich der Profi, mit all diesen Tools, cool)!

Zuest: wir sind uns einig: **alle aktuellen Betas und echten Versionen greifen nur noch auf die neue Infrastruktur zu**, gell? (gem. meiner Ankündigung will ich Ende Monat den particip-app.bfh.ch-Server ja abstellen, er erhält seit mehr als einer Woche keine Updates mehr, etc.).

Dann hast du recht: Sabine und ich haben gestern Nachmittag bei der Bilderzuordnung im Typo3 noch einige Nacharbeiten gemacht (die "Klangbrücke" hatte ja die falschen Square-Bilder drin), es kann sich dadurch sehr wohl eine Veränderung bei den Webservice-Daten ergeben haben. Tatsächlich sind auch in meinem Webservice-Snapshot von gestern 13:41 nur die 4 von dir gefundenen Werke drin; durch die Bilderzuordnungsaktion gestern später am Nachmittag wurde der Webservice mit saniert.

Meine März-Zeitstempel sind Dateiänderungszeitpunkte, der Webservice aber verwendet die Typo3-Metadaten, weil diese mit Photograph etc. versehen dann relevant sind, deshalb sind die Datumseinträge nicht vergleichbar.

Für die iOS-Version werden die Squares anhand der "Img*"-Dateien aus der Image-Beschreibung abgeleitet und heruntergeladen, also nicht alle im Image-Dienst beschriebenen Dateien heruntergeladen, das erklärt den Unterschied im Verhalten zwischen Android und iOS.

Jetzt ist für dich aber alles i.O., wenn du die neue Infrastruktur ansprichst, gell, das Problem bestand nur gestern?

Herzlichen Dank und LG Michael

**Comment by ukeller** [comment]
Ich verwende die neue Infra. 

Eine zwischen gestern 23h19 und heute mittag synchronisierte Installation auf Android wird die Square-Bilder erst sehen, wenn das Timestamp unter http://particip-app.ch/service/apiv1/image in .meta.last_changed auf den Zeitpunkt korrigiert wird, ab welchem 7 Bilder zurückgegeben wurden.

Also wenn du das Timestamp manuell auf "jetzt" setzen könntest, dann wird sich auch die bereits vorhandene Installation auf dem Gerät von Kristina korrekt synchronisieren.

**Comment by MichaelRoethlin** [comment]
OK Urs, herzlichen Dank

BISHER:

```

"description":
"Bild: Christoph Richter (2013)",
"file_type":
"images",
"identifier":
"\/katalog\/images\/img-02-016-01.jpg",
"mime_type":
"image\/jpeg",
"sorting_foreign":
1,
"title":
"Balancierender B\u00e4r",
"tstamp":
1445330040,
"uid_artwork":
49701,
"uid_file":
463

```

NEU:

```
{
"description":
"Bild: Christoph Richter (2013)",
"file_type":
"images",
"identifier":
"\/katalog\/images\/img-02-016-01.jpg",
"mime_type":
"image\/jpeg",
"sorting_foreign":
1,
"title":
"Balancierender B\u00e4r",
"tstamp":
1465398494,
"uid_artwork":
49701,
"uid_file":
463
},
```

Damit ist die Tabelle „Image“ aktualisiert auf 17:08 und die App sollte synchronisieren!!

```

{
"last_changed":
1465398494,
"last_changed_string":
"2016-06-08 17:08:14",
"oid":
"image",
"title":
"Typo3 Table sys_file_metadata",
"type":
"ServerTableData",
"uid":
9
}

```

Ich hoffe, nun klappt alles wie gewünscht??

Merci und LG Michael

**Comment by ukeller** [comment]
Ja. Jetzt ist gut.

**Comment by MichaelRoethlin** [comment]
Super und merci vielmals - doch noch ein Erfolg heute :-) :-)!!

**Comment by ukeller** [comment]
@Kristinaherbst  kannst du den prüfen und schliessen?

**Comment by Kristinaherbst** [comment]
Die Square waren mit ausgeschalteter Glühbirne- aber das habe ich korrigiert- (bei IOS waren sie dennoch da) und auch wenn sie im BACKEND nun "an" sind, erscheinen sie nicht in der App Android. Wiederum eine andere testweise Änderung in der Datenbank hat die Android ab übernommen (Feld Studium: "keine Angaben"). 
Jedoch z.B. das Objekt "Flug", erscheint nicht in der Testflight IOS; bei Android schon. In der Datenbank ist dieser Eintrag als nicht sichtbar (Glühbirne aus) markiert. Merkwürdig.
