### ISSUE TITLE
Bug Tablet IOS: Suche

### ISSUE THREAD

**Issue by Kristinaherbst** [particip-app/issues#6]
Suchfeld erscheint nicht bei Runterziehen der Liste

**Comment by MichaelRoethlin** [comment]
Komisch, auf meinem Tablet (iPad Mini sowie iPad 2) kommt das Suchfenster problemlos (wenngleich es manchmal etwas hakelt mit dem Herunterziehen). Kannst du beschreiben, wie ich das Reproduzieren kann?

**Comment by Kristinaherbst** [comment]
Ja , aber bei Android nicht…

Von: Michael Röthlin <notifications@github.com<mailto:notifications@github.com>>
Antworten an: particip-app/issues <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Donnerstag, 19. Mai 2016 12:34
An: particip-app/issues <issues@noreply.github.com<mailto:issues@noreply.github.com>>
Cc: Kristina Herbst <kristina.herbst@hkb.bfh.ch<mailto:kristina.herbst@hkb.bfh.ch>>, Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Betreff: Re: [particip-app/issues] Bug Tablet IOS: Suche (#6)

Komisch, auf meinem Tablet (iPad Mini sowie iPad 2) kommt das Suchfenster problemlos (wenngleich es manchmal etwas hakelt mit dem Herunterziehen). Kannst du beschreiben, wie ich das Reproduzieren kann?

**Comment by Kristinaherbst** [comment]
Ich habe jetzt mal bei Github die Anpassungswünsche unter ISSUES gepackt- ist das so richtig?

Lg Kristina

Von: Michael Röthlin <notifications@github.com<mailto:notifications@github.com>>
Antworten an: particip-app/issues <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Donnerstag, 19. Mai 2016 12:34
An: particip-app/issues <issues@noreply.github.com<mailto:issues@noreply.github.com>>
Cc: Kristina Herbst <kristina.herbst@hkb.bfh.ch<mailto:kristina.herbst@hkb.bfh.ch>>, Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Betreff: Re: [particip-app/issues] Bug Tablet IOS: Suche (#6)

Komisch, auf meinem Tablet (iPad Mini sowie iPad 2) kommt das Suchfenster problemlos (wenngleich es manchmal etwas hakelt mit dem Herunterziehen). Kannst du beschreiben, wie ich das Reproduzieren kann?

**Comment by Kristinaherbst** [comment]
Entschuldige, Flüchtigkeitsfehler….. Nein ich meinte tatsächlich Tablet IOS…. Muss mir erst nochmal ein Tablet besorgen um es auszuprobieren…. Sorry.

Von: Michael Röthlin <notifications@github.com<mailto:notifications@github.com>>
Antworten an: particip-app/issues <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Donnerstag, 19. Mai 2016 12:34
An: particip-app/issues <issues@noreply.github.com<mailto:issues@noreply.github.com>>
Cc: Kristina Herbst <kristina.herbst@hkb.bfh.ch<mailto:kristina.herbst@hkb.bfh.ch>>, Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Betreff: Re: [particip-app/issues] Bug Tablet IOS: Suche (#6)

Komisch, auf meinem Tablet (iPad Mini sowie iPad 2) kommt das Suchfenster problemlos (wenngleich es manchmal etwas hakelt mit dem Herunterziehen). Kannst du beschreiben, wie ich das Reproduzieren kann?

**Comment by MichaelRoethlin** [comment]
Ich glaube, ich habs: #79
