### ISSUE TITLE
Android: Absturz nach Foto

### ISSUE THREAD

**Issue by Kristinaherbst** [particip-app/issues#61]
Es gab einen Absturz:

**Comment by Kristinaherbst** [comment]
`**Steps**`
- Favoritenliste aus EInschubmenü aufgerufen
- auf der Karte alle Favor. anzeigen lassen
- dort Meldestift: neues Objekt melden / Adresse in Karte reibgetippt / Photo aufgenommen 
  **Expected result**
  App läuft weiter
  **Actual result**
  App stürzt ab

**Comment by Kristinaherbst** [comment]
gleiches Problem: bei 
**Steps**
Melden aus Detail: neues Objekt
Verwenden der Kamera 
**Expected result**
App läuft weiter
**Actual result**
App stürzt ab

**Comment by Kristinaherbst** [comment]
scheint (immer bei Verwendung des Meldesheets) stets ein Fehler zu sein.

**Comment by ukeller** [comment]
In 7(1.0).

**Comment by ukeller** [comment]
@Kristinaherbst Kannst du den schliessen?
