### ISSUE TITLE
Synchronisierung Impressum / About / Hilfe

### ISSUE THREAD

**Issue by Kristinaherbst** [particip-app/issues#62]
Werden die Inhalte aus dem backend von Impressum / About / Hilfe ebenfalls synchronisiert? Mir einscheint nicht so?

**Comment by ukeller** [comment]
Auf Android kommt das aus einem File in der App. Also nein.

**Comment by Kristinaherbst** [comment]
Wie komme ich an dieses File- wie könnte ich es verändern? Weil bei Android steht bei Impressum etc. immernoch die falsche Webadresse der Homepage. Sie darf nicht lauten www.particip-app.bfh.ch sondern nur particip-app.ch

**Comment by ukeller** [comment]
-> #64

**Comment by ukeller** [comment]
@MichaelRoethlin kommen die statischen Daten in iOS vom Service? Falls ja kannst du den Label ios wegnehmen?

**Comment by ukeller** [comment]
Aufgesplittet für Android: #73, #74, #75 
Label android entfernt.

**Comment by MichaelRoethlin** [comment]
Aufgesplittet für Backend: #76  iOS: #85
