### ISSUE TITLE
Android: Synchronisieren Material 

### ISSUE THREAD

**Issue by Kristinaherbst** [particip-app/issues#63]
Sobald ich im Backend Änderungen an der Materialverlinkung vorgenommen habe, wird diese Änderung in der App angezeigt, jedoch die gelöschten Links zum Materialarchiv, welche ich im Backend entfernt hatte- sind immernoch in der App sichtbar.

**Comment by ukeller** [comment]
Dieses Feature fehlt, da im Service die Tabellen `artwork_material_mm` und `artwork_artist_mm` kein Attribut `deleted` führen, wie das z.B. bei `kind` der Fall ist. Es gibt zwei Möglichkeiten
1. Einführen des Attributs `deleted` für  `artwork_material_mm` und `artwork_artist_mm`, dann wird das in Android ohne Änderung funktionieren
2. Änderung in Android, um die Listen abzugleichen.

**Comment by Kristinaherbst** [comment]
@MichaelRoethlin Kannst Du das ändern im Backend?

**Comment by MichaelRoethlin** [comment]
@Kristinaherbst Nein, ein Feld deleted wie von Urs vorgeschlagen kann ich nicht einfügen. Typo3 Standard ist, dass die Many-to-Many-Tabelle `artwork_material_mm` gekürzt wird und eine Zeitstempeländerung erhält. Einen Löschvorgang abzufangen und den Typo3-Systemvorgang so umzustellen ist aussichtslos.

@ukeller Bitte Variante 2 von dir. Meine Strategie auf iOS für die MM-Tabellen ist: sobald `artwork_artist_mm`, `artwork_material_mm`, `image` eine Änderung melden, muss man diese Tabellen komplett neu laden und die M:N-Beziehungen zu `artwork` neu knüpfen. (Meine Herausforderung ist derzeit noch, das alles threadsicher asynchron hinzubekommen und den Tabellenaufbau der Hauptliste elegant zu bewältigen.) Dies dünkt mich der einfachere Weg; mit `deleted` müssen in jedem Fall auch alle Beziehungen geprüft, notfalls aufgelöst werden.

```
{
"last_changed":
1465404700,
"last_changed_string":
"2016-06-08 18:51:40",
"oid":
"artwork_material_mm",
"title":
"Typo3 Table tx_participdata_artwork_material_mm",
"type":
"ServerTableData",
"uid":
8
},
```

**Comment by ukeller** [comment]
Ok. Bitte bei Urlich eingeben.

**Comment by ukeller** [comment]
Duplicate of #69
