### ISSUE TITLE
Crash wenn mehrere Bilder und Anzahl Squares > Anzahl Images

### ISSUE THREAD

**Issue by Kristinaherbst** [particip-app/issues#66]
**Gerät**: Samsung Galaxy Tablet Tab4, Android Version 4.4.2
**Zeit**: 09.6. 15:30h

**Steps**
Liste 
Detail Weltpostdenkmal 
Abbildungen Square angesehen: 3. Abbildung, 

**Expected result**
App läuft weiter (Bild wird angezeigt)
**Actual result**
App stürzt ab (App wird angehalten)

**Comment by ukeller** [comment]
Welche App-Version? Bist du auf `7(1.0), 2adc69b`?
Sehe keinen Crash-Report hier: 

https://play.google.com/apps/publish/?dev_acc=15160088022255091383#ErrorClusterListPlace:p=ch.bfh.ti.risis.particip&et=CRASH&sh=true&lr=LAST_7_DAYS

**Comment by ukeller** [comment]
Kann den Crash nachvollziehen. Bug ist valid.

**Comment by ukeller** [comment]
Fehler tritt allerdings nur auf wenn Anzahl Images(2) != Anzahl Squares(3)
Hat aber mit der Datenaktualisierung nichts zu tun.

```
curl -s http://particip-app.ch/service/apiv1/image |jq '.record|.[]| select(.uid_artwork==49703)'
{
  "uid_file": 4398,
  "title": "",
  "description": "Bild: Kristina Herbst (2016)",
  "tstamp": 1457015623,
  "uid_artwork": 49703,
  "sorting_foreign": 1,
  "file_type": "squares",
  "identifier": "/katalog/squares_generated_ios/square-02-018-02.png",
  "mime_type": "image/png"
}
{
  "uid_file": 4103,
  "title": "",
  "description": "Bild: Kristina Herbst (2016)",
  "tstamp": 1456992156,
  "uid_artwork": 49703,
  "sorting_foreign": 1,
  "file_type": "images",
  "identifier": "/katalog/images/img-02-018-02.jpg",
  "mime_type": "image/jpeg"
}
{
  "uid_file": 2477,
  "title": "Weltpostdenkmal",
  "description": "Bild: Kristina Herbst (2016)",
  "tstamp": 1447073322,
  "uid_artwork": 49703,
  "sorting_foreign": 1,
  "file_type": "thumbnail",
  "identifier": "/katalog/thumbs_generated_ios/thumb-02-018.png",
  "mime_type": "image/png"
}
{
  "uid_file": 4401,
  "title": "",
  "description": "Bild: Kristina Herbst (2016)",
  "tstamp": 1457015624,
  "uid_artwork": 49703,
  "sorting_foreign": 2,
  "file_type": "squares",
  "identifier": "/katalog/squares_generated_ios/square-02-018-03.png",
  "mime_type": "image/png"
}
{
  "uid_file": 4105,
  "title": "",
  "description": "Bild: Kristina Herbst (2016)",
  "tstamp": 1456992156,
  "uid_artwork": 49703,
  "sorting_foreign": 2,
  "file_type": "images",
  "identifier": "/katalog/images/img-02-018-03.jpg",
  "mime_type": "image/jpeg"
}
{
  "uid_file": 4400,
  "title": "",
  "description": "Bild: Kristina Herbst (2016)",
  "tstamp": 1457015624,
  "uid_artwork": 49703,
  "sorting_foreign": 3,
  "file_type": "squares",
  "identifier": "/katalog/squares_generated_ios/square-02-018-04.png",
  "mime_type": "image/png"
}
```

**Comment by Kristinaherbst** [comment]
Ok - was kann ich da tun? Oder müsste Michael oder Sabine etwas im Backend verändern?

**Comment by ukeller** [comment]
Workaround für sofort: 49703 müssen die Anzahl Bilder und die Anzahl Squares für das Kunstwerk übereinstimmen. Dies eventuell für die anderen Kunstwerk überprüfen.
Permanenter Fix: muss im Code korrigiert werden, bei Ulrich eingeben

**Comment by Kristinaherbst** [comment]
Habe alle Objekte durchprobiert in der App. "Weltpostdenkmal" ist das einzige, wo der Crash passiert. Wie erwähnt, auch wenn ich das Bild wo das dazugehörige Grossformat fehlt lösche, bleibt das Bild in der App sichtbar. (auch nach Datenaktualisierung)

**Comment by ukeller** [comment]
Bitte prüfen.

**Comment by Kristinaherbst** [comment]
vgl. Issue 71
