### ISSUE TITLE
particip-app.bfh.ch darf nicht mehr verwendet werden 

### ISSUE THREAD

**Issue by ukeller** [particip-app/issues#67]
In den Apps sowie Backend darf die alte URL particip-app.bfh.ch nicht mehr vorkommen und muss durch particip-app.ch ersetzt werden.
Ebenfalls steht an einer Stell particip-bfh.ch statt particip-app.ch.

Im Service wird im String- und Artwork-Service noch die alte URL referenziert.

curl -s http://particip-app.ch/service/apiv1/string | jq '.record[]| select(.value | contains("particip-app.bfh.ch")) | .uid'

92

curl -s http://particip-app.ch/service/apiv1/artwork | jq '.record[]| select(.studies | contains("particip-app.bfh.ch"))| .uid'

49598
49599
49648
49650
49651
49652

**Comment by MichaelRoethlin** [comment]
@Kristinaherbst Kristina, Links zu machen innerhalb der App (von Werk zu Werk, damit sich beim Draufklicken ein anderes Werk in der Detailsicht öffnet) geht so nicht! Ich habe die entsprechenden Links auf kunstfreiburg.ch zurückgehängt, das ist aber auch nicht befriedigend.

```
49598
"Freiburg-Stadt"
"Esum"
49599
"Freiburg-Stadt"
"Zylia"
49648
"St. Antoni"
"Glasfenster"
49649
"Bächlisbrunnen"
"Kreuzweg"
49650
"St. Antoni"
"Fresken"
49651
"St. Antoni"
"Mosaik"
49652
"Niedermuhren"
"Glasmalerei"
49657
"Schmitten"
"Dorfbrunnen"
49668
"Tafers"
"Kreuzweg"
49682
"Wünnewil"
"Kreuzweg"
```
