### ISSUE TITLE
Synchronisieren gelöschter und verborgender Dateien funktioniert nicht

### ISSUE THREAD

**Issue by Kristinaherbst** [particip-app/issues#68]
**Umgebung:** 
Android, Samsung Tablet Galaxy 
**Zeitpunkt:** 
13.06.2016, ca. 9 Uhr

**Version:** 
Android 
### Expected behavior
- gelöschte Datensätze auf dem Backend werden in der App nicht mehr angezeigt
- verborgen markierte Datensätze im Backend werden in der App nicht angezeigt
### Actual behaviour
- gelöschte Datensätze auf dem Backend werden dennoch in der App angezeigt
  -verborgen markierte Datensätze im Backend werden dennoch in der App angezeigt
### Steps to reproduce
- Beispiel Objekt "Flug" von Werner Witschi, ist im Backend verborgen - wird in der App angezeigt
- Beispiel Datensatz "Weltpostdenkmal", Bild: Square 02_18_04 ist gelöscht und wird angezeigt (wurde gelöscht, um das Abstürzen der App bei dazugehörigen fehlendem Img (Vollformat) zu verhindern)
- Beispiel Materialverlinkungen werden im Backend angepasst; gelöschte Verlinkungen bleiben in der App sichtbar (kumulieren sich)

**Comment by ukeller** [comment]
Bitte nicht mehrere Probleme im selben Ticket beschreiben!
Ich habe dir die Tickets in #69, #70, #71 und #72 aufgeteilt
