### ISSUE TITLE
Datenaktualisierung: Materialien von Artwork wegnehmen

### ISSUE THREAD

**Issue by ukeller** [particip-app/issues#69]
**Umgebung:**  Android generisch

**Version:** 7(1.0)
### Expected behaviour
- Gelöschte bzw. nicht referenzierte Materialien sind für den Benutzer nicht sichtbar
### Actual behaviour
- Materialien sind für den Benutzer noch sichtbar.
### Steps to reproduce
- Im Backend Material m an Artwork a anfügen
- Android, Datensynchronisation
- Android, prüfen, dass Artwork a Material m hat
- Im Backend Material m von Artwork a wegnehmen
- Android, Datensynchronisation
- Android, prüfen, dass Artwork a Material m nicht mehr hat

**Comment by ukeller** [comment]
Beispiel Materialverlinkungen werden im Backend angepasst; gelöschte Verlinkungen bleiben in der App sichtbar (kumulieren sich)

**Comment by ukeller** [comment]
Bitte prüfen.

**Comment by Kristinaherbst** [comment]
ok  bei IOS noch nicht @MichaelRoethlin
