### ISSUE TITLE
Bug Smartphone IOS: Biographie Link

### ISSUE THREAD

**Issue by Kristinaherbst** [particip-app/issues#7]
Obwohl im Backend verlinkt, werden Biographien welche mit Wiki verknüpft sind nicht angezeigt in der App. z.B. Richard Serra.

**Comment by MichaelRoethlin** [comment]
Ja, das ist tatsächlich ein Softwarefehler - auch ein leerer Sikart-Link wurde als Sikart-Link gesetzt und deshalb Wikipedia nicht eingetragen, ist korrigiert!
