### ISSUE TITLE
Datenaktualisierung: Artist von Artwork wegnehmen

### ISSUE THREAD

**Issue by ukeller** [particip-app/issues#70]
**Umgebung:**  Android generisch

**Version:** 7(1.0)
### Expected behaviour
- Gelöschte bzw. nicht referenzierte Künstler sind für den Benutzer nicht sichtbar
### Actual behaviour
- im Backend entfernte Künstler sind für den Benutzer noch sichtbar.
### Steps to reproduce
- Im Backend Künstler k an Artwork a anfügen
- Android, Datensynchronisation
- Android, prüfen, dass Artwork a Künstler k hat
- Im Backend Künstler k von Artwork a wegnehmen
- Android, Datensynchronisation
- Android, prüfen, dass Artwork a Künstler k nicht mehr hat

**Comment by ukeller** [comment]
Bitte prüfen.

**Comment by Kristinaherbst** [comment]
Oh, ich glaube da habe ich mich falsch ausgedrückt: hier ist die Erwartung, dass man den Namen des Künstlers immer sehen kann, ob er verlinkt ist oder nicht- bei einigen Künstlern gibt es kein Biographieangaben, der Name ist aber begannt. Somit muss der Name immer dastehen.... Haben wir uns da falsch verstanden? Sorry.

**Comment by ukeller** [comment]
Kannst du mir ein Kunstwerk angeben und welcher Künstler fehlt?

**Comment by Kristinaherbst** [comment]
... finde ich nicht mehr. Drum. Dies kann man umgehen, indem man den Künstler unter Artist aufnimmt aber keinen Link reinschreibt. ... Issue kann geschlossen werden; vielleicht wiedermal ein Denkfehler meinerseits...
