### ISSUE TITLE
Backend: Statische Texte / Update beim Release der App

### ISSUE THREAD

**Issue by MichaelRoethlin** [particip-app/issues#76]
**Umgebung:** 

Alle (Android, iOS, Mobile Website)
### Expected behaviour
- Texte wie Impressum, Hilfe und About, die im Typo3 geändert werden, sind beim nächsten App-Update jeweils in den Apps nachgeführt
### Actual behaviour
- Texte werden nicht nachgeführt, da separat in den Apps vorhanden resp. vor längerer Zeit hineinkopiert 
### Steps to reproduce
- Beim nächsten App-Release auf allen Plattformen dafür sorgen, dass Texte übernommen werden
- Test, dass Texte sichtbar sind

Fasst Issues #73, #74, #75 zusammen!

**Comment by ukeller** [comment]
Ich sehe in den aktuellen Daten im Vergleich zur Version in Android folgende Probleme:

## About

![about](https://cloud.githubusercontent.com/assets/2203775/16099158/041b8f20-3357-11e6-821c-3051d1638ac1.png)

## Hilfe

![hilfe](https://cloud.githubusercontent.com/assets/2203775/16099156/0419dde2-3357-11e6-86ca-a2cd3f1b75e9.png)

## Impressum

![impressum](https://cloud.githubusercontent.com/assets/2203775/16099157/041a8850-3357-11e6-8a3e-d4270c571bd1.png)

**Comment by Kristinaherbst** [comment]
@MichaelRoethlin: Kann ich diese Anpassungen im Backend machen?

**Comment by MichaelRoethlin** [comment]
@ukeller Benutzt du die für den Export der Texte die Funktion [App Strings and Labels - android de](http://particip-app.ch/service/apiv1/string/format/xml/language/0)? Ich hatte die Funktion für Lukas gebaut, aber ich weiss nicht ob sie je für den Android-Buildprozess verwendet wurde.

**Comment by MichaelRoethlin** [comment]
@Kristinaherbst Ja, Kristina, du kannst das im Typo3 unter "pARTicip-App Strings" (Liste) pflegen! Wir müssen uns nur bewusst sein, was sich wo versteckt, denn "Impressum" gibt es als Label nicht ?

**Comment by MichaelRoethlin** [comment]
Ich habe (noch eine weitere) Exportfunktion für die Texte gebaut, siehe [Link](http://particip-app.ch/service/apiv1/string/format/html/language/0)

Vorschlag: 
1. Kristina, du kannst die Bezeichnungen bereinigen, z. B. `disclaimer text` zu `impressum` umbennen und nicht benötigte Duplikate wegmachen (`about full`, oder `about`)
2. Anschliessend werfe ich maschinell die unzähligen `&nbsp;` raus, die irgendeiner mal reingemacht hat (evtl. Copy-Paste-Effekt)
3. Kristina, du kannst dann die nötigen Überarbeitungen im Typo3 übernehmen, jeweils auf [Link](http://particip-app.ch/service/apiv1/string/format/html/language/0) überprüfen, ob es richtig herauskommt.
4. Ich erweitere wenn nötig die Filterung durch den Webservice (Typo3 macht z. B. `<link>`-Elemente rein, die ich mühsam wieder in normale HTML-Links konvertieren muss)
4. Urs und ich exportieren deine geänderten Texte und bauen sie in das nächste App-Update ein.

**Comment by ukeller** [comment]
@MichaelRoethlin 
Ich benutze den Json-Service.

http://particip-app.bfh.ch/service/apiv1/string/format/xml/language/0 kannst du wegräumen.

Das aus Json bekommene Fragment wird dann in ein Template mit einem Css gepackt.

Betreffend Bilder im About unten, wäre es möglich, diese als Data-Uri einzubetten?

**Comment by MichaelRoethlin** [comment]
@ukeller Die Bilder sind jetzt testweise als Base64 eingebettet (`about` in http://particip-app.ch/service/apiv1/string/format/html/language/0 ) - geht das für dich so?

**Comment by ukeller** [comment]
OK für die Bilder. Ich habe gesehen, dass im Android noch ein HTML-Fragment und CSS
existiert. Wäre es möglich, komplettes HTML ohne externe Resourcen zu liefern?

Idealerweise, kommt vom Service alles, also Bilder, CSS, HTML in einem.
Z.B in der Form, wie das inliner macht. 

```
npm install -g inliner
inliner -v -n in.html > out.html
```

Dann muss auf Android keine Css, Fonts mehr gepflegt werden.
Ich denke mit entsprechendem CSS muss für IOS und Android im Service keine separate Lösung gemacht werden.
Schlimmstenfalls kann auf dem Client mit einem Search-Replace im Text für Android und Iphone jeweils eine
andere Body-Klasse gesetzt werden also:

```
<body class="ios" ...>
oder 
<body class="android" ...>
```

**Comment by MichaelRoethlin** [comment]
@ukeller Urs, ich denke, der bessere Ansatz ist:
- nicht jedes Label ist als HTML gedacht, deshalb kann man dies nicht pauschal allen Elementen vorne dranhängen, das wäre auch ineffizient
- zumindest für iOS haben wir jede Menge HTML-Cleanup und Styling drin, was wir berechnet (Fontsize ist ja dynamisch) den Webviews vornedranhängen, bevor das HTML angezeigt wird. Das möchte ich nicht auf den Server setzen müssen (s. unten).
- generell würde ich jetzt möglichst wenig an den iOS- und Android-Implementationen ändern wollen ...

``````
    /**
     # prepareWebViewString
     This function converts HTML coming from JSON so it can be displayed in a UIWebView.
     - Returns: Void
     - Parameter text: what should be converted to UIWebView HTML
     ```swift
     prepareWebViewString("whatever")
     */
        ...
        /// The text to return, it's use is to fill a UIWebView.
        var returnText = "<html>"
        returnText = returnText + "<head><style type='text/css'>"
        returnText = returnText + "* {"
        returnText = returnText + "   -webkit-touch-callout: none;"
        returnText = returnText + "   -webkit-user-select: none;"
        returnText = returnText + "}"
        returnText = returnText + "html {"
        returnText = returnText + "   -webkit-transform: translate3d(0,0,0);"
        returnText = returnText + "}"
        returnText = returnText + "body {"
        returnText = returnText + "   margin: 0; padding: 0; color: #333333;"
        returnText = returnText + "}"
        returnText = returnText + "ul {"
        returnText = returnText + "   margin-top:-12px;"
        returnText = returnText + "   list-style-type: none;"
        returnText = returnText + "   margin-right: 0;"
        returnText = returnText + "   margin-left: 0;"
        returnText = returnText + "   margin-bottom: 0;"
        returnText = returnText + "   padding: 1.1em;"
        returnText = returnText + "}"
        returnText = returnText + "ul > li:before {"
        returnText = returnText + "   content: '–';"
        returnText = returnText + "   position: absolute;"
        returnText = returnText + "   margin-left: -1.1em;"
        returnText = returnText + "}"
        returnText = returnText + ".main_text {"
        returnText = returnText + "   font-family: " + pARTicipAppLightFontName + ";"
        returnText = returnText + "   text-decoration:none;"
        returnText = returnText + "   font-size: "
        returnText = returnText + String(fontSize)
        returnText = returnText + "px;"
        returnText = returnText + "   color: #333333;"
        returnText = returnText + "   line-height: "
        returnText = returnText + String(1.56261 * fontSize) // @SEE: http://www.pearsonified.com/2011/12/golden-ratio-typography.php .
        returnText = returnText + "px;"
        returnText = returnText + "font-weight:normal;"
        returnText = returnText + "   text-align: left;"
        returnText = returnText + "   -webkit-transform: translate3d(0,0,0);"
        returnText = returnText + "}"
        returnText = returnText + "h2 {"
        returnText = returnText + "   font-family: " + pARTicipAppLightFontName + ";"
        returnText = returnText + "   text-decoration:none;"
        returnText = returnText + "   font-size: "
        returnText = returnText + String(h2FontSize)
        returnText = returnText + "px;"
        returnText = returnText + "   color: #333333;"
        //        returnText = returnText + "   line-height: "
        //        returnText = returnText + String(1.56261 * h2FontSize) // @SEE: http://www.pearsonified.com/2011/12/golden-ratio-typography.php .
        //        returnText = returnText + "px;"
        returnText = returnText + "font-weight:normal;"
        returnText = returnText + "   text-align: left;"
        returnText = returnText + "   -webkit-transform: translate3d(0,0,0);"
        returnText = returnText + "}"
        returnText = returnText + "h4 {"
        returnText = returnText + "   font-family: " + pARTicipAppLightFontName + ";"
        returnText = returnText + "   text-decoration:none;"
        returnText = returnText + "   font-size: "
        returnText = returnText + String(h4FontSize)
        returnText = returnText + "px;"
        returnText = returnText + "   color: #333333;"
        //        returnText = returnText + "   line-height: "
        //        returnText = returnText + String(1.56261 * h2FontSize) // @SEE: http://www.pearsonified.com/2011/12/golden-ratio-typography.php .
        //        returnText = returnText + "px;"
        returnText = returnText + "font-weight:normal;"
        returnText = returnText + "   text-align: left;"
        returnText = returnText + "   -webkit-transform: translate3d(0,0,0);"
        returnText = returnText + "}"
        returnText = returnText + "b {"
        returnText = returnText + "   font-family: " + pARTicipAppMediumFontName + ";"
        returnText = returnText + "   font-weight:normal;"
        returnText = returnText + "}"
        returnText = returnText + "h4 {"
        returnText = returnText + "   font-family: " + pARTicipAppMediumFontName + ";"
        returnText = returnText + "   font-weight:normal;"
        returnText = returnText + "}"
        returnText = returnText + "a {color: #333333;}"

        returnText = returnText + "</style></head>" +
            "<body> <span class='main_text'>" +
            text +
        "</span></body></html>"
        returnText = returnText.stringByReplacingOccurrencesOfString("mso-ascii-font-family: Cambria; mso-fareast-font-family: Cambria; mso-hansi-font-family: Cambria; mso-bidi-font-family: Cambria;", withString: "", options: NSStringCompareOptions.LiteralSearch, range: nil)
        returnText = returnText.stringByReplacingOccurrencesOfString("font: 7.0pt", withString: "", options: NSStringCompareOptions.LiteralSearch, range: nil)
        returnText = returnText.stringByReplacingOccurrencesOfString("font-size: 8pt;", withString: "", options: NSStringCompareOptions.LiteralSearch, range: nil)
        returnText = returnText.stringByReplacingOccurrencesOfString("font-size: 10pt;", withString: "", options: NSStringCompareOptions.LiteralSearch, range: nil)
        returnText = returnText.stringByReplacingOccurrencesOfString("font-size:11.0pt;font-family:Calibri; mso-ascii-theme-font:major-latin;mso-hansi-theme-font:major-latin", withString: "", options: NSStringCompareOptions.LiteralSearch, range: nil)
        returnText = returnText.stringByReplacingOccurrencesOfString("font-family: arial,helvetica,sans-serif;", withString: "", options: NSStringCompareOptions.LiteralSearch, range: nil)
        returnText = returnText.stringByReplacingOccurrencesOfString("font-family: Arial;", withString: "", options: NSStringCompareOptions.LiteralSearch, range: nil)
        returnText = returnText.stringByReplacingOccurrencesOfString("mso-bidi-font-style:normal", withString: "", options: NSStringCompareOptions.LiteralSearch, range: nil)
        returnText = returnText.stringByReplacingOccurrencesOfString("<em>", withString: "", options: NSStringCompareOptions.LiteralSearch, range: nil)
        returnText = returnText.stringByReplacingOccurrencesOfString("</em>", withString: "", options: NSStringCompareOptions.LiteralSearch, range: nil)
        returnText = returnText.stringByReplacingOccurrencesOfString("<strong>", withString: "", options: NSStringCompareOptions.LiteralSearch, range: nil)
        returnText = returnText.stringByReplacingOccurrencesOfString("</strong>", withString: "", options: NSStringCompareOptions.LiteralSearch, range: nil)
        return returnText
....
``````

**Comment by ukeller** [comment]
Das mit dem vollen HTML war nur für die Texte about, disclaimer und help gemeint.
Aber bin einverstanden, dass im Moment nur minimale Anpassungen gemacht werden. Auch wenn dies eine duplizieren der Logik auf den jeweiligen Clients bedeutet.

**Comment by MichaelRoethlin** [comment]
Alles klar, merci vielmals, Urs!

**Comment by ukeller** [comment]
Bitte auf Android prüfen.

**Comment by Kristinaherbst** [comment]
Die Texte im Android aktuell können so belassen werden. Was mich jedoch an dieser Stelle wundert ist, dass der apiv service ein ABOUT anzeigt, welches in der App nicht mehr vorgesehen ist (langer Text) und auch im Backend gelöscht ist?  
Ich habe im Backend: ABOUT IMPRESSUM und HELP belassen- alle anderen gelöscht. Jedoch fehlt nun im Backend bei ABOUT das SNF und BFH Logo? Oder sehe ich das einfach nicht?

**Comment by ukeller** [comment]
Die Bilder sind in ABOUT nicht vorhanden. In der APP siehst du sie, da die statischen Texte wie oben beschrieben: `...Texte wie Impressum, Hilfe und About, die im Typo3 geändert werden, sind beim nächsten App-Update jeweils in den Apps nachgeführt...` jeweils erst mit einer neuen Version nachgeführt werden.

@MichaelRoethlin die Base64-codierten Bilder in ABOUT aus http://particip-app.ch/service/apiv1/string sind nicht mehr vorhanden. Kannst du prüfen?

**Comment by ukeller** [comment]
@Kristinaherbst kann ich das Label `android` entfernen? Aus meiner Sicht sind die Daten auf Android nachgeführt.

**Comment by MichaelRoethlin** [comment]
Salut zusammen 
@Kristinaherbst 
Die Bilder sind rausgelöscht worden, vermutlich aus Versehen, bei deiner letzten Überarbeitung; die Einbettung als "Encoded Binary" ist wirklich heikel und eignet sich eigentlich überhaupt nicht für die Nachbearbeitung in einem HTML-Editor (ist einfach technisch für die Einbindung in der App einfacher) ... 

Zum Glück haben wir Typo3, alles ist versioniert und kann per Klick wiederhergestellt werden. Was hast du bei About geändert (ausser es in ABOUT umzubenennen), kann ich einfach auf den Stand von heute Morgen zurück?

Merci und LG, Michael

<img width="703" alt="about" src="https://cloud.githubusercontent.com/assets/4992205/16991517/116607d6-4e9c-11e6-8e71-70a57ee3a2e1.png">

**Comment by Kristinaherbst** [comment]
Ja die Inhalte sind richtig. Ich habe ABOUT , IMPRESSUM und HELP in grossen Lettern geschrieben um den Überblick zu behalten welche die richtigen sind. An den Texten habe ich also nichts geändert- warum die Bilder hops gegangen sind, kann ich mir nicht erklären, sorry

**Comment by MichaelRoethlin** [comment]
Macht nichts :-) ... wie gesagt ist es sehr heikel in der Bearbeitung (fast nur im HTML-Modus möglich)!

Ich habe es gerne wiederhergestellt, einfach about --> ABOUT geändert. Jetzt sind unter http://particip-app.ch/service/apiv1/string/format/html/language/0 die Logos wieder sichtbar.

**Comment by ukeller** [comment]
Nehme Android aus den Labeln.
