### ISSUE TITLE
Backend: Test Cases für den Test der Reaktion von Clients auf Änderungen im Backend (hidden, deleted)

### ISSUE THREAD

**Issue by MichaelRoethlin** [particip-app/issues#77]
- Test Cases gem. [Aufstellung](https://github.com/particip-app/issues/blob/master/DataProvisioning.md#appendix-c-reference-test-cases)
- Aufruf resp. Umstellung über URL http://particip-app.ch/service/apiv1/fakeState/00 ...
- Alle Bearbeitungszustände im Lebenszyklus eines Werks sollen über URL einstellt werden, am Beispiel des Artwork UID 49715: Trojanisches Pferd

**Comment by MichaelRoethlin** [comment]
Fertiggestellt:
- Bsp: http://particip-app.ch/service/apiv1/fakeState/reset setzt das Werk zurück auf (Server) deleted
- Bsp: http://particip-app.ch/service/apiv1/fakeState/04 generiert den Fall 1 Thumbnail, 2 Squares, 1 Image [(s. Issue 66)](https://github.com/particip-app/issues/issues/66)
- Bsp: http://particip-app.ch/service/apiv1/fakeState/11 generiert ein voll ausgestaltetes Werk mit 2 Künstlern, etc.
- Alle Zeitstempel werden im Übergang realistisch erzeugt
- Jede volle Stunde wird das Artwork im Backend wieder zurückgesetzt, d.h. gelöscht
- Alle aktuellen Zustände des Werks können auf http://catalog.particip-app.ch/de/artwork/49715 parallel in echt betrachtet werden

**Comment by Kristinaherbst** [comment]
vgl. Issue 71
