### ISSUE TITLE
iOS: Meldeformular allg.

### ISSUE THREAD

**Issue by Kristinaherbst** [particip-app/issues#8]
Das Formular zu Melden (Global als auch Detail) ist in dieser Form für den User sehr unübersichtlich, da nicht klar wird, von welchem Objekt beim Melden die Rede ist. Es fehlt quasi ein Feld, wo man das vorausgewählte Objekt (wenn man von Detail kommt) voreingetragen hat oder die Möglichkeit es einzutragen.

**Comment by MichaelRoethlin** [comment]
Vergleich Android - iOS:

**Android**
- Gleiches Icon, gleiche Funktionen für globales und objektbezogenes Melden
  - Schaden melden (mit anschl. Auswahlmenü zum Werk [Auswahlmenü oder gar noch nicht erfasst]); zeigt Listeneintrag zum Werk sowie Karte mit Platz des Werks
  - Fehler im Text melden
  - Falsche Koordinaten melden
  - Neues Kunstwerk melden
- _Sehr_ komplexe Menüführung; Absturz der App, sobald Art der Meldung (oberstes Dropdown) geändert wird

—> Implementierung ist für iOS (dort werden globales und objektbezogenes Melden mit 2 unterschiedlichen Icons abgebildet; es macht nicht Sinn, alle 4 Teilfunktionen hinter jedem Icon abzubilden) nicht sinnvoll

**iOS**
- implementiert nach Screendesign 1.2, Seite 10
- Globales Melden
  - Neues Objekt
  - Fehler im Text melden
  - Falsche Koordinaten melden
  - Schaden melden
- Objektbezogenes Melden
  - Beschreiben Sie den Schaden am resp. Ihre Beobachtung zum Werk

—> Überlegungen gem. Stand Screendesign sind nicht durchdacht, ist so nicht befriedigend

**Vorschlag iOS neu:**
- Globales Melden
  - Neues Objekt
- Objektbezogenes Melden
  - Fehler im Text melden
  - Falsche Koordinaten melden
  - Schaden/Beobachtung melden (Beschreiben Sie den Schaden am resp. Ihre Beobachtung zum Werk)
- Inhalte
  - Nur „Neues Objekt“ erhält Karte
  - Beim Objektbezogenen Melden wird ganz zuoberst zur Erinnerung die Beschreibung „xxx von yyy in zzz“ gezeigt

Vorschläge (TestFlight 1.0.2 Build 2):

**Melden aus der Detailansicht:**

![screenshot 2016 05 22 18 02 48](https://cloud.githubusercontent.com/assets/4992205/15454991/75c93ec4-2047-11e6-9a16-bba9d9c3e72c.png)

**Melden global:**

![screenshot 2016 05 22 17 55 11](https://cloud.githubusercontent.com/assets/4992205/15454992/75fa719c-2047-11e6-9b23-a7ec38fa7cb2.png)

**Comment by Kristinaherbst** [comment]
ok- das ist so besser ; )

**Comment by MichaelRoethlin** [comment]
Prima, dann lassen wir das mal so, ich schliesse.
