### ISSUE TITLE
IOS Smartphone: Inhalte waren nicht synchron beim 1. Start

### ISSUE THREAD

**Issue by Kristinaherbst** [particip-app/issues#95]
**Umgebung:** 
IOS IPhone 5s
**Zeitpunkt:** 
Do 7.7 20 Uhr
**Version:** 
IOS Testflight
### Steps to reproduce
- alte Version Testflight gelöscht
- Download Testflight vom 7.7

**Comment by Kristinaherbst** [comment]
Ist es für den Release nicht möglich, dass man beim Download die aktuellsten Daten bekommt?

**Comment by MichaelRoethlin** [comment]
Doch, ich baue für ein Release jeweils die aktuellsten Daten vom Server ein, das ist so!

**Comment by MichaelRoethlin** [comment]
OK, mit der neusten Server-Überarbeitung und (damit verbunden) durch das sehr stark verfeinerte und nun [nahezu] fehlerfreie Synchronisieren werden viel weniger Daten übertragen und das Risiko für negative Beeinflussungen des App-Starts gesenkt. Ich baue mal in den nächsten TestFlight 10 die Synchronisation beim Start ein und teste intensiv in gestörten Datenverbindungsumfeld!
