### ISSUE TITLE
IOS Smartphone: Anzeige des Titels des Werkes beim Melden zu wenig Platz

### ISSUE THREAD

**Issue by Kristinaherbst** [particip-app/issues#96]
**Umgebung:** 
IOS IPhone 5s
**Zeitpunkt:** 
7.7. 20 Uhr
**Version:** 
testflight vom 7.7
### Actual behaviour
- \- Meldesheet Detail : Titel des Werkes wird nicht vollständig angezeigt, "Bsp. Vertikaler und horizontaler Metallkasten..."; der Titel ist in der unteren Zeile abgeschnitten. 
- Vorschlag: mit Punkten auslaufen lassen?
## \- Detail - dort auf Melden- 
-

**Comment by MichaelRoethlin** [comment]
OK - ich habe das Feld scrollbar gemacht, man kann jetzt innerhalb vom Feld den ganzen Text lesen (wenn man will; andernfalls zieht man ausserhalb einfach das ganze Fenster).

![simulator screen shot 10 07 2016 11 13 32](https://cloud.githubusercontent.com/assets/4992205/16712710/8c3da6b8-468f-11e6-9ae9-d85bf8935e4f.png)
