### ISSUE TITLE
IOS Smartphone: Suche verschiebt Liste

### ISSUE THREAD

**Issue by Kristinaherbst** [particip-app/issues#97]
**Umgebung:** 
IOS Iphone 5s
**Zeitpunkt:** 
7.7 20 Uhr
**Version:** 
Tesflight vom 7.7
### Actual behaviour
- wenn man im Einschubmenü Suche ausgewählt hat, wird die Liste verschoben (grosse weisse Fläche) 
- Auch nach mehrmaligen klicken auf Suche im Einschub verschwindet die Ansicht nicht
### Steps to reproduce
- ins Detail eines Werkes gehen; danach auf Liste

**Comment by Kristinaherbst** [comment]
- beim vierten Versuch, ist das Problem nicht mehr aufgetreten?

**Comment by MichaelRoethlin** [comment]
Ja, ich würde das auf das ältere Geräte und iOS 9.3 zurückführen. Auch auf meinem alten iPad 2 mit der Standard-Mail-App passiert beim Suchen genau das, dass die Fenster verschoben zurückbleiben und nicht dynamisch zurückwippen.
